Readme update
NVIDIA/GenerativeAIExamples pull request #16
Opened 2023-12-18 16:39 UTC by jliberma

2023-12-18 17:45 UTC, shubhadeepd requested changes

2023-12-18 17:45 UTC, shubhadeepd commented on RetrievalAugmentedGeneration/README.md
> +09150764b74a   triton-inference-server   Up 15 minutes (unhealthy)
This docker name has changed to `llm-inference-server`

2023-12-18 17:45 UTC, shubhadeepd commented on RetrievalAugmentedGeneration/README.md
> +
Should this be empty or point to some location?

2023-12-18 17:45 UTC, shubhadeepd commented on RetrievalAugmentedGeneration/README.md
> +$ cd deploy/
This should be `cd deploy/compose`

2023-12-18 18:18 UTC, shubhadeepd commented on RetrievalAugmentedGeneration/README.md
> +a839261973b8   milvus-etcd               Up 40 minutes (healthy)
evaluation container is missing from this list.

2023-12-19 04:04 UTC, jliberma commented on RetrievalAugmentedGeneration/README.md
> +a839261973b8   milvus-etcd               Up 40 minutes (healthy)
I did not deploy it. I do not want it deployed by default. It should be optional. Is it deployed by default now?

2023-12-19 04:06 UTC, jliberma commented on RetrievalAugmentedGeneration/README.md
> +
its a placeholder but I can delete it, I agree it looks unfinished

2023-12-19 07:12 UTC, shubhadeepd commented on RetrievalAugmentedGeneration/README.md
> +a839261973b8   milvus-etcd               Up 40 minutes (healthy)
yes it is deployed by default.

2023-12-19 20:09 UTC, shubhadeepd commented
Closing this PR, to consolidate changes in a separate commit.

2023-12-19 20:09 UTC, closed without merging